name: ed25519_dart
description: Pure Dart implementation of Ed25519 - public-key signature system.
version: 1.0.0
homepage: https://github.com/semolex
author: Oleksii Semeshchuk <semolex@live.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
   pointycastle: "^0.10.0+5"

dev_dependencies:
  test: ^0.12.0
